The goal of this analysis is defining if the detected attack must be considered benign or malicious. To do so, here we try to draw a carattererization of the attack and find some relation between user if there are

In [1]:
import pandas as pd

In [2]:
DATA_PATH = "../../data/history/dataset/test.csv"

df = pd.read_csv(DATA_PATH)

df

,id_res,package,file,who_introduce,when_introduce,where_introduce,who_remove,when_remove,where_remove,line_tracking
0,var_circuit,skqulacs,./tests/test_circuit.py,ikanago,Tue Jul 13 17:04:06 2021,9f322ac6e4165d455ea6bc1ca824c088ac9cd736,ikanago,Tue Jul 13 15:33:02 2021,7ce131ef2f4180e85899c757d42851e9443e1497,9->9->_
1,var_circuit,skqulacs,./tests/test_circuit.py,ikanago,Tue Jul 13 17:04:06 2021,9f322ac6e4165d455ea6bc1ca824c088ac9cd736,NaN,NaN,NaN,12->12->11->11->11->11->11->11->11->11->11->11...
2,var_circuit,skqulacs,./tests/test_circuit.py,ikanago,Tue Jul 13 17:04:06 2021,9f322ac6e4165d455ea6bc1ca824c088ac9cd736,NaN,NaN,NaN,8->8->8->8->8->8->8->8->8->8->8->8->52->52->8-...
3,var_circuit,skqulacs,./tests/test_circuit.py,ikanago,Tue Jul 13 17:04:06 2021,9f322ac6e4165d455ea6bc1ca824c088ac9cd736,NaN,NaN,NaN,11->11->10->10->10->10->10->10->10->10->10->10...
4,var_circuit,skqulacs,./tests/test_circuit.py,ikanago,Tue Jul 13 17:04:06 2021,9f322ac6e4165d455ea6bc1ca824c088ac9cd736,NaN,NaN,NaN,7->7->7->7->7->7->7->7->7->7->7->7->51->51->7-...
...,...,...,...,...,...,...,...,...,...,...
5728,var_Observable,skqulacs,./skqulacs/qnn/regressor.py,Gruntrexpewrus,Thu Dec 1 17:19:50 2022,98d388fb01134eb236f5f2d95961966b0317df07,NaN,NaN,NaN,74->74->74->74->...
5729,var_Observable,skqulacs,./skqulacs/qnn/regressor.py,Gruntrexpewrus,Thu Dec 1 17:19:50 2022,98d388fb01134eb236f5f2d95961966b0317df07,NaN,NaN,NaN,54->54->54->54->...
5730,var_Observable,skqulacs,./skqulacs/qnn/regressor.py,Gruntrexpewrus,Thu Dec 1 17:19:50 2022,98d388fb01134eb236f5f2d95961966b0317df07,NaN,NaN,NaN,116->116->116->116->...
5731,var_Observable,skqulacs,./skqulacs/qnn/regressor.py,Gruntrexpewrus,Thu Dec 1 17:19:50 2022,98d388fb01134eb236f5f2d95961966b0317df07,NaN,NaN,NaN,198->198->198->198->...
5732,var_Observable,skqulacs,./skqulacs/qnn/regressor.py,Gruntrexpewrus,Thu Dec 1 17:19:50 2022,98d388fb01134eb236f5f2d95961966b0317df07,NaN,NaN,NaN,225->225->225->225->...

# Attack characterization

In [3]:
def is_function(x: str) -> bool:
    for string in ["func", "afunc", "patch_decorator_import", "patch_decorator_usage", "contextmanager_import", "contextmanager_usage", "overwrite_method_class", "eval_call", "exec_call", "with_statement"]:
        if string in x:
            return True
    return False

In [6]:
df["target"] = df["id_res"].apply(
    lambda x: "class" if "class_" in x
    else "variable" if "var_" in x
    else "function" if is_function(x)
    else "other"
)

df.groupby("target").size().reset_index(name="count")

     target  count
0  variable   5733

# Users relations

In [18]:
df_relationships = df.loc[::,["id_res", "package", "file", "who_introduce", "who_remove"]]

df_relationships.dropna(inplace=True)

df_relationships.drop_duplicates(inplace=True)

df_relationships.groupby(["who_introduce", "who_remove"]).size().reset_index(name="count")

     who_introduce      who_remove  count
0   Gruntrexpewrus  Gruntrexpewrus      3
1   Gruntrexpewrus         ikanago      2
2           Toshio          Toshio      6
3           Toshio           WATLE      3
4           Toshio         ikanago      3
5            WATLE         Satoshi      2
6            WATLE          Toshio      5
7            WATLE           WATLE      6
8            WATLE          Wataru      8
9            WATLE      forest1040      2
10           WATLE         ikanago     12
11           WATLE       kosukemtr      4
12          Wataru           WATLE     14
13          Wataru          Wataru     23
14          Wataru      forest1040      2
15          Wataru         ikanago     13
16          Wataru       kosukemtr     12
17      forest1040          Toshio      3
18      forest1040           WATLE      4
19      forest1040      forest1040      2
20      forest1040         ikanago      5
21      forest1040       kosukemtr      3
22      herring101           WATLE      1
23      herring101         ikanago      1
24         ikanago  Gruntrexpewrus      4
25         ikanago          Toshio      4
26         ikanago           WATLE     12
27         ikanago          Wataru      8
28         ikanago         ikanago     51
29         ikanago       kosukemtr      4
30       kosukemtr           WATLE      1
31       kosukemtr          Wataru     10
32       kosukemtr         ikanago      3
33       kosukemtr       kosukemtr      3